---
title: "FAS1002_projet-final"
bibliography: references.bib
---

Le projet a pour objectif de constater les relations existantes entre le PIB par habitant, l'espérance de vie et l'émissions de CO2 et de gaz à effet de serre entre les pays. Les données utilisées sont issues de deux banques de données différentes : @owidCO2 et @gapminder

Une première partie se concentre sur l'analyse descriptive des données (voir onglet *Exploration des données*) où l'on retrouve différentes statistiques sur les données. Les variables de chacune des banques de données sont observées individuellement afin d'en observer les tendances.

La seconde partie se concentre sur une analyse plus technique où les variables sont mises en relation afin de mettre en évidence des relations potentielles (voir onglet *Analyse technique*).

## Vous pourrez inclure des graphiques

Comme la classique pyramide à la ci-dessous par exemple:

```{r pie, fig.cap='Une très belle tarte', tidy=FALSE}
par(mar = c(0, 1, 0, 1))
pie(
  c(280, 60, 20),
  c('Ciel', 'Côté ensoleillé de la pyramide', 'Côté ombragé de la pyramide'),
  col = c('#0292D8', '#F7EA39', '#C4B632'),
  init.angle = -50, border = NA
)
```

<aside>Quand même très cool, non? Vous pouvez mettre des annotations sur le côté!</aside>

## Remerciements {.appendix}

J'aimerais remercier toute la cohorte du cours FAS1002 de l'automne 2022 pour leur ouverture et efforts tout au long de la session!

@owidenergy
